### ISSUE TITLE
will not turn on

### ISSUE THREAD

**Issue by Gijj3235** [DMAD777/tray-indicators#1]
have tried turning on and off, changing colors, turning individual options on and off, logging in and out, and restarting RL client. still will not appear in tray.

**Comment by DMAD777** [comment]
I see that you closed the issue shortly after opening it. Did you manage to fix the issue? If not which operation system are you currently using? Did you check if the try icon is inside the "Up" arrow in windows 10 (https://i.imgur.com/NKBIxjQ.png).
