### ISSUE TITLE
Possible over initialization or Memory Leak

### ISSUE THREAD

**Issue by nbuck3** [DMAD777/tray-indicators#2]
The following image shows the system tray and icon overload which can result in the client becoming unresponsive. 

![image](https://user-images.githubusercontent.com/33386140/188652757-9f704874-c85c-452a-a46c-4d714b2f4a3a.png)

**Comment by DMAD777** [comment]
Hey @nbuck3, I managed to find the source of the issue and will be writing up a fix shortly.

**Comment by DMAD777** [comment]
Should be fixed in 4b013362c005bc1d082a10ec0c40f3c2f0362c9a. As I no longer actively play I don't have membership so I cannot test the absorption icons.

Please allow some time for it to be merged in the plugin-hub.
