### ISSUE TITLE
Infinitely recreating absorption icons

### ISSUE THREAD

**Issue by Soitora** [DMAD777/tray-indicators#3]
Possibly related to #2

![image](https://github.com/DMAD777/tray-indicators/assets/10836780/8621235e-3a67-4891-b871-0826cf74cf5b)

![image](https://github.com/DMAD777/tray-indicators/assets/10836780/bb9904b4-70d9-462e-a72b-c9ccf07e0eb2)

**Comment by DMAD777** [comment]
I've implemented a fix. Please allow some time for it to be merged into the plugin hub repo.
