### ISSUE TITLE
Suggestion: Add cannon ball count to tray

### ISSUE THREAD

**Issue by victordegnbol** [DMAD777/tray-indicators#5]
Hi!

Thank you for the great application. I have a suggestion: add functionality for current cannon ball count to the plugin. Makes it easy to see at a glance when you need to fill up your cannon.

Best regards

**Comment by DMAD777** [comment]
Hey

Thank you for your suggestion. The feature is complete and will soon be merged. It may take some time for it to be merged into the plugin hub repo.

![Screenshot](https://github.com/DMAD777/tray-indicators/assets/19578055/92f6ec3d-5d4d-41b1-aebf-05196f0fb4bb)

**Comment by victordegnbol** [comment]
Wow, thank you so much for adding my suggestion.. And so quickly!!

Best regards
